---
- name: Reload Nginx
  service:
    name: "{{ nginx_service_name }}"
    state: reloaded
    enabled: yes
  become: yes
  become_user: root

- name: Restart Nginx
  service:
    name: "{{ nginx_service_name }}"
    state: restarted
    enabled: yes
  become: yes
  become_user: root
